[versions]
agp = "9.1.1"
androidTools = "32.1.1"
asm = "9.9.1"
coreStubs = "1.3.0"
jadb = "9083b5096f"
guava = "30.1.1-jre"
kotlin = "2.3.20"
serialization = "1.11.0"

[libraries]
android-tools-sdk = { group = "com.android.tools", name = "sdk-common", version.ref = "androidTools" }
android-sdklib = { module = "com.android.tools:sdklib", version.ref = "androidTools" }
android-tools-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
asm = { group = "org.ow2.asm", name = "asm", version.ref = "asm" }
asm-tree = { group = "org.ow2.asm", name = "asm-tree", version.ref = "asm" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
jadb = { group = "com.github.vidstige", name = "jadb", version.ref = "jadb" }
coreStubs-model-provider = { group = "com.github.flixclusiveorg.core-stubs", name = "model-provider", version.ref = "coreStubs" }
compose-compiler-gradle-plugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }